import type { MatchWithDetails } from "@/lib/types/api";

export function createMockApplication(
  overrides: Partial<MatchWithDetails> = {},
): MatchWithDetails {
  return {
    id: "match-1",
    userId: "user-1",
    jobId: "job-1",
    aiScore: 0.85,
    status: "APPLIED",
    appliedAt: new Date("2026-02-01"),
    hiredAt: null,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-02-01"),
    user: {
      id: "user-1",
      type: "JOBSEEKER",
      phone: "090-1234-5678",
      name: "テスト太郎",
      location: "東京都",
      lat: 35.6,
      lng: 139.7,
      language: "ja",
      trustScore: 50,
      companyId: null,
      createdAt: new Date("2026-01-01"),
      updatedAt: new Date("2026-01-01"),
      skills: [],
    },
    job: {
      id: "job-1",
      companyId: "company-1",
      title: "倉庫内軽作業スタッフ",
      description: "商品の仕分け作業",
      salaryMin: 10000,
      salaryMax: 15000,
      location: "東京都品川区",
      lat: 35.6,
      lng: 139.7,
      shiftType: "FULL_TIME",
      urgency: "NORMAL",
      status: "ACTIVE",
      createdAt: new Date("2026-01-01"),
      updatedAt: new Date("2026-01-01"),
      company: {
        id: "company-1",
        name: "テスト株式会社",
        industry: "LOGISTICS",
        size: 50,
        address: "東京都品川区",
        lat: 35.6,
        lng: 139.7,
        verified: true,
        trustScore: 80,
        createdAt: new Date("2026-01-01"),
        updatedAt: new Date("2026-01-01"),
      },
    },
    ...overrides,
  };
}
